### ISSUE TITLE
Uploader with Auth Type Negotiate 

### ISSUE THREAD

**Issue by wdmillard** [EMSL-MSC/pacifica-uploader#17]
Need to support Kerberos single source sign on.  This is the error I get when enabled and accessed from an external user.

ValueError at /
Unknown auth scheme "Negotiate"
Request Method:	GET
Request URL:	http://127.0.0.1:8000/
Django Version:	1.9.13
Exception Type:	ValueError
Exception Value:	
Unknown auth scheme "Negotiate"
Exception Location:	./home/views.py in user_from_request, line 80
Python Executable:	/opt/myemsldev1-uploader/virtualenv/bin/uwsgi
Python Version:	2.7.8
Python Path:	
['.',
 '',
 '/opt/myemsldev1-uploader/virtualenv/lib64/python2.7/site-packages',
 '/opt/myemsldev1-uploader/virtualenv/lib64/python27.zip',
 '/opt/myemsldev1-uploader/virtualenv/lib64/python2.7',
 '/opt/myemsldev1-uploader/virtualenv/lib64/python2.7/plat-linux2',
 '/opt/myemsldev1-uploader/virtualenv/lib64/python2.7/lib-tk',
 '/opt/myemsldev1-uploader/virtualenv/lib64/python2.7/lib-old',
 '/opt/myemsldev1-uploader/virtualenv/lib64/python2.7/lib-dynload',
 '/opt/rh/python27/root/usr/lib64/python2.7',
 '/opt/rh/python27/root/usr/lib/python2.7',
 '/opt/myemsldev1-uploader/virtualenv/lib/python2.7/site-packages',
 '/opt/myemsldev1-uploader/source']
Server time:	Mon, 5 Jun 2017 19:14:06 +0000

**Comment by GitBytes** [comment]
https://pypi.python.org/pypi/requests-negotiate/1.4.1

**Comment by GitBytes** [comment]
@wdmillard This seems to be coming up again now that we are migrating to full kerberos SSO integration for Data Hub. We might have to address this sooner than later or continue to kick the can down the road and not have SSO for uploader interfaces.

```
django.request:ERROR Internal Server Error: / :/uploader/virtualenv/lib/python2.7/site-packages/django/core/handlers/base.py:284
Traceback (most recent call last):
File "/opt/datahubdev01-uploader/virtualenv/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
response = self.process_exception_by_middleware(e, request)
File "/opt/datahubdev01-uploader/virtualenv/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "./home/views.py", line 121, in populate_upload_page
retval = login(request)
File "./home/views.py", line 445, in login
err_str = login_user_locally(request)
File "./home/views.py", line 394, in login_user_locally
username = user_from_request(request)
File "./home/views.py", line 90, in user_from_request
raise ValueError('Unknown auth scheme \"%s\"' % scheme)
ValueError: Unknown auth scheme "Negotiate"
```
